# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the document type (e.g., 'PASSPORT', 'BIRTH_CERT')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Passport', 'Birth Certificate')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the document type",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this document type is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Document Types",
                "db_table": "document_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="VisaRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requirement_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the requirement (e.g., 'MIN_SALARY', 'AGE_LIMIT')",
                        max_length=100,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility Requirement"),
                            ("document", "Document Requirement"),
                            ("fee", "Fee Information"),
                            ("processing_time", "Processing Time"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of requirement",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the requirement"
                    ),
                ),
                (
                    "condition_expression",
                    models.JSONField(
                        help_text="JSON Logic expression representing the requirement condition"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this requirement is mandatory",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Visa Requirements",
                "db_table": "visa_requirements",
                "ordering": ["requirement_code"],
            },
        ),
        migrations.CreateModel(
            name="VisaRuleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this rule version becomes effective",
                    ),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this rule version expires (NULL means current)",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this rule version is published and available for use",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this rule version is soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this rule version was deleted",
                        null=True,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this rule version was published",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version number for optimistic locking to prevent concurrent modification conflicts",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Visa Rule Versions",
                "db_table": "visa_rule_versions",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="VisaType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("UK", "United Kingdom"),
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                        ],
                        db_index=True,
                        help_text="Jurisdiction this visa type belongs to",
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for the visa type (e.g., 'SKILLED_WORKER', 'STUDENT')",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Skilled Worker Visa', 'Student Visa')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the visa type", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this visa type is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Visa Types",
                "db_table": "visa_types",
                "ordering": ["jurisdiction", "code"],
            },
        ),
        migrations.CreateModel(
            name="VisaDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this document is mandatory",
                    ),
                ),
                (
                    "conditional_logic",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSON Logic for conditional requirements (e.g., dependants)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        help_text="The document type required",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_requirements",
                        to="rules_knowledge.documenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visa Document Requirements",
                "db_table": "visa_document_requirements",
            },
        ),
    ]
