# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_ingestion", "0003_initial"),
        ("rules_knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visaruleversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this rule version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rule_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visaruleversion",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published this rule version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_rule_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visaruleversion",
            name="source_document_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The document version this rule was extracted from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rule_versions",
                to="data_ingestion.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="visaruleversion",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this rule version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_rule_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visarequirement",
            name="rule_version",
            field=models.ForeignKey(
                help_text="The rule version this requirement belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="rules_knowledge.visaruleversion",
            ),
        ),
        migrations.AddField(
            model_name="visadocumentrequirement",
            name="rule_version",
            field=models.ForeignKey(
                help_text="The rule version this document requirement belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_requirements",
                to="rules_knowledge.visaruleversion",
            ),
        ),
        migrations.AddIndex(
            model_name="visatype",
            index=models.Index(
                fields=["jurisdiction", "is_active"],
                name="visa_types_jurisdi_a60497_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visatype",
            unique_together={("jurisdiction", "code")},
        ),
        migrations.AddField(
            model_name="visaruleversion",
            name="visa_type",
            field=models.ForeignKey(
                help_text="The visa type this rule version applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rule_versions",
                to="rules_knowledge.visatype",
            ),
        ),
        migrations.AddIndex(
            model_name="visarequirement",
            index=models.Index(
                fields=["rule_version", "is_mandatory"],
                name="visa_requir_rule_ve_d8eec3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visarequirement",
            index=models.Index(
                fields=["rule_type", "is_mandatory"],
                name="visa_requir_rule_ty_712bd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visarequirement",
            index=models.Index(
                fields=["rule_version", "requirement_code"],
                name="visa_requir_rule_ve_559e7c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visarequirement",
            unique_together={("rule_version", "requirement_code")},
        ),
        migrations.AddIndex(
            model_name="visadocumentrequirement",
            index=models.Index(
                fields=["rule_version", "mandatory"],
                name="visa_docume_rule_ve_a7bb4a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visadocumentrequirement",
            unique_together={("rule_version", "document_type")},
        ),
        migrations.AddIndex(
            model_name="visaruleversion",
            index=models.Index(
                fields=["visa_type", "effective_from", "effective_to"],
                name="visa_rule_v_visa_ty_563765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visaruleversion",
            index=models.Index(
                fields=["is_published", "effective_from"],
                name="visa_rule_v_is_publ_5b7161_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visaruleversion",
            index=models.Index(
                fields=["is_deleted", "is_published"],
                name="visa_rule_v_is_dele_d69969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visaruleversion",
            index=models.Index(
                fields=["visa_type", "is_published", "effective_from", "effective_to"],
                name="visa_rule_v_visa_ty_f15a74_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="visaruleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="effective_to_after_effective_from",
            ),
        ),
    ]
