# Generated by Django 5.2.10 on 2026-01-14 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to the stored file", max_length=500
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="uploaded",
                        help_text="Current status of the document",
                        max_length=20,
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text from OCR processing",
                        null=True,
                    ),
                ),
                (
                    "classification_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score for document type classification (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Expiry date extracted from document (e.g., passport expiry, visa expiry)",
                        null=True,
                    ),
                ),
                (
                    "extracted_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted metadata from document (names, dates, numbers, etc.)",
                        null=True,
                    ),
                ),
                (
                    "content_validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status of content validation against case facts",
                        max_length=20,
                    ),
                ),
                (
                    "content_validation_details",
                    models.JSONField(
                        blank=True,
                        help_text="Details of content validation (matched fields, mismatches, etc.)",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Case Documents",
                "db_table": "case_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR"),
                            ("classification", "Classification"),
                            ("validation", "Validation"),
                            ("content_validation", "Content Validation"),
                            ("requirement_match", "Requirement Match"),
                            ("authenticity", "Authenticity Check"),
                        ],
                        db_index=True,
                        help_text="Type of check performed",
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        help_text="Result of the check",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Additional details about the check result",
                        null=True,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="Who/what performed the check (AI, human reviewer, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Document Checks",
                "db_table": "document_checks",
                "ordering": ["-created_at"],
            },
        ),
    ]
