# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document_handling", "0001_initial"),
        ("immigration_cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="case",
            field=models.ForeignKey(
                help_text="The case this document belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="immigration_cases.case",
            ),
        ),
    ]
