# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document_handling", "0002_initial"),
        ("rules_knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="document_type",
            field=models.ForeignKey(
                help_text="The type of document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_documents",
                to="rules_knowledge.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="documentcheck",
            name="case_document",
            field=models.ForeignKey(
                help_text="The document this check belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="document_handling.casedocument",
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["case", "status"], name="case_docume_case_id_a79dad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["document_type", "status"],
                name="case_docume_documen_a00e51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcheck",
            index=models.Index(
                fields=["case_document", "check_type"],
                name="document_ch_case_do_e169d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcheck",
            index=models.Index(
                fields=["result", "-created_at"], name="document_ch_result_9937b0_idx"
            ),
        ),
    ]
