# Generated by Django 5.2.10 on 2026-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_handling", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("needs_attention", "Needs Attention"),
                ],
                db_index=True,
                default="uploaded",
                help_text="Current status of the document",
                max_length=20,
            ),
        ),
    ]
