# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("immigration_cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Payment Created"),
                            ("status_changed", "Status Changed"),
                            ("gateway_initiated", "Gateway Initiated"),
                            ("gateway_verified", "Gateway Verified"),
                            ("webhook_received", "Webhook Received"),
                            ("retry_attempted", "Retry Attempted"),
                            ("refund_initiated", "Refund Initiated"),
                            ("refund_completed", "Refund Completed"),
                            ("notification_sent", "Notification Sent"),
                            ("error_occurred", "Error Occurred"),
                        ],
                        db_index=True,
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous payment status (if status changed)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        help_text="New payment status (if status changed)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("message", models.TextField(help_text="Event message or description")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event metadata (gateway response, error details, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Payment History",
                "db_table": "payment_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event ID from payment gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Payment provider (stripe, paypal, adyen)",
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type from gateway", max_length=100
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Original webhook payload"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this webhook was processed",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Webhook Events",
                "db_table": "payment_webhook_events",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("CHF", "Swiss Franc"),
                            ("NZD", "New Zealand Dollar"),
                            ("SGD", "Singapore Dollar"),
                            ("HKD", "Hong Kong Dollar"),
                            ("NGN", "Nigerian Naira"),
                            ("AED", "UAE Dirham"),
                            ("ZAR", "South African Rand"),
                            ("INR", "Indian Rupee"),
                        ],
                        db_index=True,
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of retry attempts for failed payments",
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Maximum number of retry attempts"
                    ),
                ),
                (
                    "last_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last retry attempt",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("adyen", "Adyen"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        help_text="Payment provider used",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Version number for optimistic locking",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this payment is soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When this payment was deleted", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case this payment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="immigration_cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
