# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this event (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment",
            field=models.ForeignKey(
                help_text="The payment this history entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhookevent",
            name="payment",
            field=models.ForeignKey(
                help_text="The payment this webhook event belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="payments.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["case", "status"], name="payments_case_id_3f2d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_status_db6b16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["payment", "-created_at"], name="payment_his_payment_a55466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenthistory",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="payment_his_event_t_cae135_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhookevent",
            index=models.Index(
                fields=["payment", "-processed_at"],
                name="payment_web_payment_5f5b81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhookevent",
            index=models.Index(
                fields=["provider", "event_id"], name="payment_web_provide_5a81c4_idx"
            ),
        ),
    ]
