# Generated by Cursor on 2026-01-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_payment_user(apps, schema_editor):
    """
    Backfill Payment.user from Payment.case.user for existing rows.
    """
    Payment = apps.get_model("payments", "Payment")
    for payment in Payment.objects.select_related("case", "case__user").all():
        if payment.user_id:
            continue
        if payment.case_id:
            payment.user_id = payment.case.user_id
            payment.save(update_fields=["user"])


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="The user this payment belongs to (required for pre-case payments)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="case",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="The case this payment belongs to (nullable for pre-case payments)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="immigration_cases.case",
            ),
        ),
        migrations.RunPython(backfill_payment_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="The user this payment belongs to (required for pre-case payments)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                db_index=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "status"], name="payments_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "case", "status"], name="payments_user_case_status_idx"),
        ),
    ]

