# Generated by Django 5.2.10 on 2026-01-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_user_and_nullable_case"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_user_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_user_case_status_idx",
        ),
    ]
