# Generated by Django 5.2.10 on 2026-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_case_fee_plan_required"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_case_id_351dd3_idx",
            old_name="payments_ca_purpose_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_case_id_2148ac_idx",
            old_name="payments_case_purpose_plan_status_idx",
        ),
        migrations.RenameIndex(
            model_name="pricingitem",
            new_name="pricing_ite_kind_5dec4c_idx",
            old_name="pricing_items_kind_active_idx",
        ),
        migrations.RenameIndex(
            model_name="pricingitemprice",
            new_name="pricing_ite_currenc_9be805_idx",
            old_name="pricing_prices_currency_amount_idx",
        ),
        migrations.AlterField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("case_fee", "Case Fee"),
                    ("reviewer_addon", "Reviewer Add-on"),
                    ("ai_calls_addon", "AI Calls Add-on"),
                ],
                db_index=True,
                default="case_fee",
                help_text="What this payment is for (case fee vs add-ons like reviewer)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pricingitemprice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("JPY", "Japanese Yen"),
                    ("CHF", "Swiss Franc"),
                    ("NZD", "New Zealand Dollar"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("NGN", "Nigerian Naira"),
                    ("AED", "UAE Dirham"),
                    ("ZAR", "South African Rand"),
                    ("INR", "Indian Rupee"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
    ]
