# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_ingestion", "0001_enable_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the extracted text for change detection",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        help_text="Extracted text content (cleaned HTML, PDF text, etc.)"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this version was extracted",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (page numbers, sections, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document Versions",
                "db_table": "document_versions",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleValidationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the validation task",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Notes from the reviewer", null=True
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the review was completed",
                        null=True,
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="SLA deadline for completing this validation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Rule Validation Tasks",
                "db_table": "rule_validation_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        db_index=True,
                        help_text="Full URL of the fetched document",
                        max_length=1000,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this document was fetched",
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        help_text="Raw content as fetched (HTML, JSON, PDF text, etc.)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="text/html",
                        help_text="Content type (text/html, application/json, application/pdf, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "http_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code from the fetch operation",
                        null=True,
                    ),
                ),
                (
                    "fetch_error",
                    models.TextField(
                        blank=True, help_text="Error message if fetch failed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Source Documents",
                "db_table": "source_documents",
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable name for the data source (e.g., 'UK Gov Immigration Pages')",
                        max_length=255,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL for the data source (e.g., 'https://www.gov.uk/api/content')",
                        max_length=500,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("UK", "United Kingdom"),
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                        ],
                        db_index=True,
                        help_text="Jurisdiction this source belongs to (UK, US, CA, AU)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this source is currently being monitored",
                    ),
                ),
                (
                    "crawl_frequency",
                    models.CharField(
                        default="daily",
                        help_text="How often to check for updates (daily, weekly, hourly)",
                        max_length=50,
                    ),
                ),
                (
                    "last_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last time this source was successfully fetched",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Data Sources",
                "db_table": "data_sources",
                "ordering": ["jurisdiction", "name"],
                "indexes": [
                    models.Index(
                        fields=["jurisdiction", "is_active"],
                        name="data_source_jurisdi_b5d392_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentDiff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diff_text",
                    models.TextField(
                        help_text="Unified diff showing changes between versions"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("minor_text", "Minor Text Change"),
                            ("requirement_change", "Requirement Change"),
                            ("fee_change", "Fee Change"),
                            ("processing_time_change", "Processing Time Change"),
                            ("major_update", "Major Update"),
                        ],
                        db_index=True,
                        default="minor_text",
                        help_text="Classification of the type of change detected",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "new_version",
                    models.ForeignKey(
                        help_text="New version of the document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_as_new",
                        to="data_ingestion.documentversion",
                    ),
                ),
                (
                    "old_version",
                    models.ForeignKey(
                        help_text="Previous version of the document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diffs_as_old",
                        to="data_ingestion.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document Diffs",
                "db_table": "document_diffs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(help_text="Text content of this chunk"),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        default=0,
                        help_text="Index of this chunk within the document (0-based)",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Vector embedding for semantic search",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (visa_code, effective_date, jurisdiction, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        help_text="Document version this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="data_ingestion.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document Chunks",
                "db_table": "document_chunks",
                "ordering": ["document_version", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="ParsedRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visa_code",
                    models.CharField(
                        db_index=True,
                        help_text="Visa type code (e.g., 'SKILLED_WORKER', 'STUDENT')",
                        max_length=100,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility Requirement"),
                            ("document", "Document Requirement"),
                            ("fee", "Fee Information"),
                            ("processing_time", "Processing Time"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of rule extracted",
                        max_length=50,
                    ),
                ),
                (
                    "extracted_logic",
                    models.JSONField(
                        help_text="JSON Logic expression representing the rule condition"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the requirement"
                    ),
                ),
                (
                    "source_excerpt",
                    models.TextField(
                        help_text="Original text excerpt from the document"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Confidence score (0.0 to 1.0) for the extraction quality",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Validation status of the parsed rule",
                        max_length=20,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="LLM model used for extraction (e.g., 'gpt-4-turbo-preview')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "llm_model_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the LLM model used",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of tokens used for this extraction",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Estimated cost in USD for this extraction",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Processing time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of error if parsing failed (e.g., 'rate_limit', 'timeout')",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        help_text="The document version this rule was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_rules",
                        to="data_ingestion.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parsed Rules",
                "db_table": "parsed_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleParsingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("parse_started", "Parse Started"),
                            ("parse_completed", "Parse Completed"),
                            ("parse_failed", "Parse Failed"),
                            ("rule_created", "Rule Created"),
                            ("validation_task_created", "Validation Task Created"),
                            ("cache_hit", "Cache Hit"),
                            ("cache_miss", "Cache Miss"),
                            ("rate_limit_wait", "Rate Limit Wait"),
                            ("pii_detected", "PII Detected"),
                            ("pii_redacted", "PII Redacted"),
                        ],
                        db_index=True,
                        help_text="Action performed",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        help_text="Status: success, failure, warning",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Human-readable message", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata (tokens, cost, processing time, etc.)",
                        null=True,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Error type if action failed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if action failed",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent of the request (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        help_text="Document version being processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="data_ingestion.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rule Parsing Audit Logs",
                "db_table": "rule_parsing_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
