# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_ingestion", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleparsingauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered the action (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rule_parsing_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rulevalidationtask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Reviewer assigned to validate this rule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rule_validation_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rulevalidationtask",
            name="parsed_rule",
            field=models.ForeignKey(
                help_text="The parsed rule being validated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_tasks",
                to="data_ingestion.parsedrule",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="data_source",
            field=models.ForeignKey(
                help_text="The data source this document was fetched from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_documents",
                to="data_ingestion.datasource",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="source_document",
            field=models.ForeignKey(
                help_text="The source document this version was extracted from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_versions",
                to="data_ingestion.sourcedocument",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdiff",
            index=models.Index(
                fields=["old_version", "new_version"],
                name="document_di_old_ver_382f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentdiff",
            index=models.Index(
                fields=["change_type", "-created_at"],
                name="document_di_change__df70df_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentdiff",
            unique_together={("old_version", "new_version")},
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document_version", "chunk_index"],
                name="document_ch_documen_c4122d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parsedrule",
            index=models.Index(
                fields=["document_version", "status"],
                name="parsed_rule_documen_a787c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parsedrule",
            index=models.Index(
                fields=["visa_code", "status"], name="parsed_rule_visa_co_35c7e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parsedrule",
            index=models.Index(
                fields=["status", "-confidence_score"],
                name="parsed_rule_status_7718f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruleparsingauditlog",
            index=models.Index(
                fields=["document_version", "action"],
                name="rule_parsin_documen_4cec10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ruleparsingauditlog",
            index=models.Index(
                fields=["action", "status"], name="rule_parsin_action_e3413b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleparsingauditlog",
            index=models.Index(
                fields=["created_at", "status"], name="rule_parsin_created_aca1a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleparsingauditlog",
            index=models.Index(
                fields=["error_type"], name="rule_parsin_error_t_56208e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rulevalidationtask",
            index=models.Index(
                fields=["parsed_rule", "status"], name="rule_valida_parsed__cd1dec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rulevalidationtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="rule_valida_assigne_94d17f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rulevalidationtask",
            index=models.Index(
                fields=["status", "sla_deadline"], name="rule_valida_status_263846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["data_source", "-fetched_at"],
                name="source_docu_data_so_aa1e56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcedocument",
            index=models.Index(
                fields=["source_url"], name="source_docu_source__1a0a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["source_document", "-extracted_at"],
                name="document_ve_source__294f64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["content_hash"], name="document_ve_content_7d6015_idx"
            ),
        ),
    ]
