# Generated by Django 5.2.10 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="datasource",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="datasource",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentdiff",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="documentdiff",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="documentdiff",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsedrule",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="parsedrule",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="parsedrule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rulevalidationtask",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="rulevalidationtask",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="rulevalidationtask",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleparsingauditlog",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="ruleparsingauditlog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="ruleparsingauditlog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

