# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.CharField(db_index=True, max_length=50)),
                ("logger_name", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("pathname", models.TextField(blank=True, null=True)),
                ("lineno", models.IntegerField(blank=True, null=True)),
                ("func_name", models.CharField(blank=True, max_length=255, null=True)),
                ("process", models.IntegerField(blank=True, null=True)),
                ("thread", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_logs",
            },
        ),
    ]
