# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                ("password", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("reviewer", "Reviewer"),
                        ],
                        db_index=True,
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("login_count", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "last_assigned_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last time reviewer was assigned a review (for round-robin assignment)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="custom_user_group",
                        related_query_name="user",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="custom_user_permissions",
                        related_query_name="user",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 code (e.g., 'NG', 'GB', 'US')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Country name (e.g., 'Nigeria', 'United Kingdom')",
                        max_length=200,
                    ),
                ),
                (
                    "has_states",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this country has states/provinces (e.g., Canada, Australia, US)",
                    ),
                ),
                (
                    "is_jurisdiction",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this country is a supported immigration jurisdiction",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="countries_code_df63e8_idx"),
                    models.Index(
                        fields=["is_jurisdiction", "is_active"],
                        name="countries_is_juri_b4adfb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reset_counter", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_resets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StateProvince",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="State/Province code (e.g., 'ON', 'NSW')",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full name (e.g., 'Ontario', 'New South Wales')",
                        max_length=200,
                    ),
                ),
                (
                    "has_nomination_program",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this state/province has an immigration nomination program",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states_provinces",
                        to="users_access.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "States/Provinces",
                "db_table": "states_provinces",
                "ordering": ["country", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserDeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=128, unique=True)),
                ("fingerprint", models.CharField(blank=True, max_length=256)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_mfa_verified", models.BooleanField(default=False)),
                (
                    "last_active",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_device_sessions",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date of birth for age-based eligibility checks",
                        null=True,
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="User has given consent for data processing",
                    ),
                ),
                (
                    "consent_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="When consent was given", null=True
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's nationality/country of citizenship",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nationals",
                        to="users_access.country",
                    ),
                ),
                (
                    "state_province",
                    models.ForeignKey(
                        blank=True,
                        help_text="State/Province of nationality (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="users_access.stateprovince",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("two_factor_auth", models.BooleanField(db_index=True, default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email_notifications",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("sms_notifications", models.BooleanField(db_index=True, default=True)),
                (
                    "push_notifications",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "notify_case_status_updates",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when case status changes (evaluated, reviewed, etc.)",
                    ),
                ),
                (
                    "notify_eligibility_results",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when eligibility check results are ready",
                    ),
                ),
                (
                    "notify_document_status",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when documents are verified, rejected, or need attention",
                    ),
                ),
                (
                    "notify_missing_documents",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify about missing required documents",
                    ),
                ),
                (
                    "notify_rule_changes",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when immigration rules change for user's visa type",
                    ),
                ),
                (
                    "notify_review_updates",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when human review is assigned or completed",
                    ),
                ),
                (
                    "notify_review_assignments",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify when new review is assigned (for reviewers)",
                    ),
                ),
                (
                    "notify_sla_deadlines",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify about approaching SLA deadlines (for reviewers)",
                    ),
                ),
                (
                    "notify_rule_validation_tasks",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Notify about new rule validation tasks (for reviewers/admins)",
                    ),
                ),
                ("dark_mode", models.BooleanField(db_index=True, default=False)),
                (
                    "language",
                    models.CharField(
                        db_index=True,
                        default="en",
                        help_text="Preferred language code (e.g., 'en', 'fr', 'es')",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's timezone (e.g., 'America/New_York', 'Europe/London')",
                        max_length=50,
                    ),
                ),
                (
                    "data_sharing_consent",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Consent for anonymized data sharing for analytics",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Consent to receive marketing/promotional emails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("case_status_update", "Case Status Update"),
                            ("eligibility_result_ready", "Eligibility Result Ready"),
                            ("document_status", "Document Status"),
                            ("document_failed", "Document Failed"),
                            ("review_assigned", "Review Assigned"),
                            ("review_completed", "Review Completed"),
                            ("rule_change", "Rule Change"),
                            ("missing_documents", "Missing Documents"),
                            ("sla_deadline", "SLA Deadline"),
                            ("rule_validation_task", "Rule Validation Task"),
                            ("payment_status", "Payment Status"),
                        ],
                        db_index=True,
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the user has read this notification",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when notification was read",
                        null=True,
                    ),
                ),
                (
                    "related_entity_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of related entity (e.g., 'case', 'review', 'document')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "related_entity_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of related entity",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional metadata (JSON)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_c4e471_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_id_63f199_idx",
                    ),
                    models.Index(
                        fields=["related_entity_type", "related_entity_id"],
                        name="notificatio_related_83c4d7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp", models.CharField(max_length=6, null=True)),
                (
                    "endpoint_token",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_otp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "otp"], name="otps_user_id_8c7b49_idx"
                    ),
                    models.Index(fields=["expires_at"], name="otps_expires_f6308f_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stateprovince",
            index=models.Index(
                fields=["country", "code"], name="states_prov_country_e30783_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stateprovince",
            index=models.Index(
                fields=["has_nomination_program"], name="states_prov_has_nom_e20038_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stateprovince",
            unique_together={("country", "code")},
        ),
        migrations.AddIndex(
            model_name="userdevicesession",
            index=models.Index(
                fields=["user", "revoked"], name="user_device_user_id_1251ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["nationality"], name="user_profil_nationa_aa6420_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["state_province"], name="user_profil_state_p_768182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["date_of_birth"], name="user_profil_date_of_38efd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersetting",
            index=models.Index(
                fields=["email_notifications"], name="user_settin_email_n_2de936_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersetting",
            index=models.Index(
                fields=["notify_case_status_updates"],
                name="user_settin_notify__975f80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersetting",
            index=models.Index(
                fields=["notify_eligibility_results"],
                name="user_settin_notify__770881_idx",
            ),
        ),
    ]
