# Generated by Django migration
# Based on AI Call Service models

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immigration_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, db_index=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('terminated', 'Terminated')], db_index=True, default='created', help_text='Current status of the call session', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='When context was built and call became ready', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When call actually started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When call ended', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Actual call duration in seconds', null=True)),
                ('context_bundle', models.JSONField(blank=True, help_text='Pre-built case context bundle (sealed before call starts)', null=True)),
                ('context_version', models.IntegerField(default=1, help_text='Version number of context bundle (increments when rebuilt)')),
                ('context_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of context bundle for deterministic audits', max_length=64, null=True)),
                ('webrtc_session_id', models.CharField(blank=True, db_index=True, help_text='WebRTC session identifier', max_length=255, null=True)),
                ('warnings_count', models.IntegerField(default=0, help_text='Number of guardrail warnings')),
                ('refusals_count', models.IntegerField(default=0, help_text='Number of off-scope refusals')),
                ('escalated', models.BooleanField(default=False, help_text='Whether call was escalated to human review')),
                ('version', models.IntegerField(db_index=True, default=1, help_text='Version number for optimistic locking')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(db_index=True, help_text='The immigration case this call is scoped to', on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='immigration_cases.case')),
                ('user', models.ForeignKey(db_index=True, help_text='The user who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, db_index=True)),
                ('summary_text', models.TextField(help_text='Main summary text')),
                ('key_questions', models.JSONField(default=list, help_text='List of key questions asked during the call')),
                ('action_items', models.JSONField(default=list, help_text='List of action items identified')),
                ('missing_documents', models.JSONField(default=list, help_text='List of missing documents identified')),
                ('suggested_next_steps', models.JSONField(default=list, help_text='List of suggested next steps (non-binding)')),
                ('total_turns', models.IntegerField(help_text='Total number of turns in the call')),
                ('total_duration_seconds', models.IntegerField(help_text='Total call duration in seconds')),
                ('topics_discussed', models.JSONField(default=list, help_text='List of topics discussed')),
                ('attached_to_case', models.BooleanField(default=False, help_text='Whether summary has been attached to case timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, db_index=True)),
                ('turn_number', models.IntegerField(db_index=True, help_text='Sequential turn number (1, 2, 3, ...)')),
                ('turn_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], db_index=True, help_text='Type of turn (user, ai, system)', max_length=10)),
                ('text', models.TextField(help_text='Transcribed text or AI response')),
                ('speech_confidence', models.FloatField(blank=True, help_text='Speech-to-text confidence score (0.0-1.0)', null=True)),
                ('ai_model', models.CharField(blank=True, help_text='AI model used (e.g., \'gpt-4\', \'claude-3\')', max_length=100, null=True)),
                ('ai_prompt_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of prompt (stored by default for privacy)', max_length=64, null=True)),
                ('ai_prompt_used', models.TextField(blank=True, help_text='Full prompt sent to AI (only stored when guardrails triggered or admin requested)', null=True)),
                ('guardrails_triggered', models.BooleanField(default=False, help_text='Whether guardrails were triggered for this turn')),
                ('guardrails_action', models.CharField(blank=True, help_text='Guardrails action taken (refused, warned, escalated)', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this turn occurred')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of this turn in seconds', null=True)),
                ('storage_tier', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], db_index=True, default='hot', help_text='Storage tier: hot (recent, frequently accessed) or cold (archived)', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When transcript was moved to cold storage', null=True)),
                ('call_session', models.ForeignKey(db_index=True, help_text='The call session this turn belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transcript_turns', to='ai_calls.callsession')),
            ],
            options={
                'db_table': 'call_transcripts',
                'ordering': ['call_session', 'turn_number'],
            },
        ),
        migrations.CreateModel(
            name='CallAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, db_index=True)),
                ('event_type', models.CharField(choices=[('guardrail_triggered', 'Guardrail Triggered'), ('refusal', 'Refusal'), ('warning', 'Warning'), ('escalation', 'Escalation'), ('timebox_warning', 'Timebox Warning'), ('auto_termination', 'Auto Termination'), ('manual_termination', 'Manual Termination'), ('state_transition', 'State Transition'), ('invalid_transition_attempt', 'Invalid Transition Attempt')], db_index=True, help_text='Type of audit event', max_length=50)),
                ('description', models.TextField(help_text='Description of the event')),
                ('user_input', models.TextField(blank=True, help_text='User input that triggered the event (if applicable)', null=True)),
                ('ai_response', models.TextField(blank=True, help_text='AI response (if applicable)', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata about the event', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('call_session', models.ForeignKey(db_index=True, help_text='The call session this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ai_calls.callsession')),
            ],
            options={
                'db_table': 'call_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='summary',
            field=models.ForeignKey(blank=True, help_text='Post-call summary (generated after call ends)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_session', to='ai_calls.callsummary'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['case', 'status'], name='call_sessio_case_id_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['user', 'status'], name='call_sessio_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', '-created_at'], name='call_sessio_status_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['webrtc_session_id'], name='call_sessio_webrtc_idx'),
        ),
        migrations.AddIndex(
            model_name='calltranscript',
            index=models.Index(fields=['call_session', 'turn_number'], name='call_transc_session_turn_idx'),
        ),
        migrations.AddIndex(
            model_name='calltranscript',
            index=models.Index(fields=['call_session', 'timestamp'], name='call_transc_session_time_idx'),
        ),
        migrations.AddIndex(
            model_name='callauditlog',
            index=models.Index(fields=['call_session', '-created_at'], name='call_audit_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='callauditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='call_audit_event_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['created', 'ready', 'in_progress', 'completed', 'expired', 'terminated'])), name='valid_call_session_status'),
        ),
        migrations.AlterUniqueTogether(
            name='calltranscript',
            unique_together={('call_session', 'turn_number')},
        ),
    ]
