# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_calls", "0001_initial"),
        ("immigration_cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="case",
            field=models.ForeignKey(
                help_text="The immigration case this call is scoped to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sessions",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="callsession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent session if this is a retry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retry_sessions",
                to="ai_calls.callsession",
            ),
        ),
    ]
