# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_calls", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="user",
            field=models.ForeignKey(
                help_text="The user who initiated the call",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callauditlog",
            name="call_session",
            field=models.ForeignKey(
                help_text="The call session this audit log belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="ai_calls.callsession",
            ),
        ),
        migrations.AddField(
            model_name="callsummary",
            name="call_session",
            field=models.OneToOneField(
                help_text="The call session this summary belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_summary",
                to="ai_calls.callsession",
            ),
        ),
        migrations.AddField(
            model_name="callsession",
            name="summary",
            field=models.ForeignKey(
                blank=True,
                help_text="Post-call summary (generated after call ends)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_with_summary",
                to="ai_calls.callsummary",
            ),
        ),
        migrations.AddField(
            model_name="calltranscript",
            name="call_session",
            field=models.ForeignKey(
                help_text="The call session this turn belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcript_turns",
                to="ai_calls.callsession",
            ),
        ),
        migrations.AddIndex(
            model_name="callauditlog",
            index=models.Index(
                fields=["call_session", "-created_at"],
                name="call_audit__call_se_8bde3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callauditlog",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="call_audit__event_t_40bdd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["case", "status"], name="call_sessio_case_id_90dcb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["user", "status"], name="call_sessio_user_id_a3c7f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["status", "-created_at"], name="call_sessio_status_7bdbd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["webrtc_session_id"], name="call_sessio_webrtc__b8f546_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "created",
                            "ready",
                            "in_progress",
                            "completed",
                            "expired",
                            "terminated",
                        ],
                    )
                ),
                name="valid_call_session_status",
            ),
        ),
        migrations.AddIndex(
            model_name="calltranscript",
            index=models.Index(
                fields=["call_session", "turn_number"],
                name="call_transc_call_se_8edbc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calltranscript",
            index=models.Index(
                fields=["call_session", "timestamp"],
                name="call_transc_call_se_11cd12_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calltranscript",
            unique_together={("call_session", "turn_number")},
        ),
    ]
