# Generated by Django 5.2.10 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_calls", "0003_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="callsession",
            name="valid_call_session_status",
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "created",
                            "ready",
                            "in_progress",
                            "completed",
                            "expired",
                            "terminated",
                            "failed",
                        ],
                    )
                ),
                name="valid_call_session_status",
            ),
        ),
    ]

