# Generated by Django 5.2.10 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_calls", "0004_callsession_add_failed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="last_heartbeat_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time the client sent a heartbeat (liveness tracking)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="callauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("guardrail_triggered", "Guardrail Triggered"),
                    ("refusal", "Refusal"),
                    ("warning", "Warning"),
                    ("escalation", "Escalation"),
                    ("system_error", "System Error"),
                    ("timebox_warning", "Timebox Warning"),
                    ("auto_termination", "Auto Termination"),
                    ("manual_termination", "Manual Termination"),
                    ("state_transition", "State Transition"),
                    ("invalid_transition_attempt", "Invalid Transition Attempt"),
                ],
                db_index=True,
                help_text="Type of audit event",
                max_length=50,
            ),
        ),
    ]

