# Generated by Django 5.2.10 on 2026-01-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_calls", "0006_callsummaries_allow_blank_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("ready", "Ready"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("terminated", "Terminated"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                help_text="Current status of the call session",
                max_length=20,
            ),
        ),
    ]
