# Generated by Django 5.2.10 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_calls", "0007_alter_callsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="calltranscript",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calltranscript",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="calltranscript",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="callsummary",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callsummary",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="callauditlog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callauditlog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]

