# Generated by Django 5.2.10 on 2026-01-14 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="The excerpt from the document that was cited"
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        help_text="Relevance score for this citation (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "AI Citations",
                "db_table": "ai_citations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIReasoningLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField(help_text="The prompt sent to the LLM")),
                ("response", models.TextField(help_text="The response from the LLM")),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the LLM model used (e.g., 'gpt-4', 'claude-3')",
                        max_length=100,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of tokens used in the API call",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "AI Reasoning Logs",
                "db_table": "ai_reasoning_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("not_eligible", "Not Eligible"),
                            ("requires_review", "Requires Review"),
                            ("missing_facts", "Missing Facts"),
                        ],
                        db_index=True,
                        help_text="Final eligibility outcome",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score (0.0 to 1.0) for the outcome",
                    ),
                ),
                (
                    "reasoning_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the reasoning for this outcome",
                        null=True,
                    ),
                ),
                (
                    "missing_facts",
                    models.JSONField(
                        blank=True,
                        help_text="List of missing facts if outcome is 'missing_facts'",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Eligibility Results",
                "db_table": "eligibility_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
