# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_decisions", "0001_initial"),
        ("data_ingestion", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicitation",
            name="document_version",
            field=models.ForeignKey(
                help_text="The document version cited",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_citations",
                to="data_ingestion.documentversion",
            ),
        ),
    ]
