# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_decisions", "0002_initial"),
        ("immigration_cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireasoninglog",
            name="case",
            field=models.ForeignKey(
                help_text="The case this reasoning log belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reasoning_logs",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="aicitation",
            name="reasoning_log",
            field=models.ForeignKey(
                help_text="The reasoning log this citation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citations",
                to="ai_decisions.aireasoninglog",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityresult",
            name="case",
            field=models.ForeignKey(
                help_text="The case this result belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_results",
                to="immigration_cases.case",
            ),
        ),
    ]
