# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_decisions", "0003_initial"),
        ("rules_knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilityresult",
            name="rule_version",
            field=models.ForeignKey(
                help_text="The rule version used for evaluation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_results",
                to="rules_knowledge.visaruleversion",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityresult",
            name="visa_type",
            field=models.ForeignKey(
                help_text="The visa type evaluated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_results",
                to="rules_knowledge.visatype",
            ),
        ),
        migrations.AddIndex(
            model_name="aireasoninglog",
            index=models.Index(
                fields=["case", "-created_at"], name="ai_reasonin_case_id_993c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicitation",
            index=models.Index(
                fields=["reasoning_log", "-created_at"],
                name="ai_citation_reasoni_f6a50d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eligibilityresult",
            index=models.Index(
                fields=["case", "visa_type"], name="eligibility_case_id_e137d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eligibilityresult",
            index=models.Index(
                fields=["outcome", "-created_at"], name="eligibility_outcome_9985d5_idx"
            ),
        ),
    ]
