# Generated by Django 5.2.10 on 2026-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_decisions", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilityresult",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="eligibilityresult",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="eligibilityresult",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aireasoninglog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="aireasoninglog",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="aireasoninglog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="aireasoninglog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aicitation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="aicitation",
            name="version",
            field=models.IntegerField(db_index=True, default=1, help_text="Version number for optimistic locking"),
        ),
        migrations.AddField(
            model_name="aicitation",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="aicitation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

