# Generated by Django 5.2.10 on 2026-01-14 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("UK", "United Kingdom"),
                            ("US", "United States"),
                            ("CA", "Canada"),
                            ("AU", "Australia"),
                        ],
                        db_index=True,
                        help_text="Jurisdiction for this immigration case",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("evaluated", "Evaluated"),
                            ("awaiting_review", "Awaiting Review"),
                            ("reviewed", "Reviewed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the case",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Version number for optimistic locking",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this case is soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When this case was deleted", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Cases",
                "db_table": "cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fact_key",
                    models.CharField(
                        db_index=True,
                        help_text="Key for the fact (e.g., 'salary', 'age', 'nationality')",
                        max_length=255,
                    ),
                ),
                (
                    "fact_value",
                    models.JSONField(
                        help_text="Value of the fact (can be string, number, boolean, etc.)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User Provided"),
                            ("ai", "AI Derived"),
                            ("reviewer", "Reviewer Corrected"),
                        ],
                        db_index=True,
                        default="user",
                        help_text="Source of the fact",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Case Facts",
                "db_table": "case_facts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status before change",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        help_text="New status after change", max_length=20
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the status change", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the status change",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Case Status History",
                "db_table": "case_status_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
