# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("immigration_cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casefact",
            name="case",
            field=models.ForeignKey(
                help_text="The case this fact belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facts",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casestatushistory",
            name="case",
            field=models.ForeignKey(
                help_text="The case whose status changed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="casestatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who initiated the status change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["user", "status"], name="cases_user_id_c07d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["jurisdiction", "status"], name="cases_jurisdi_cf3266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["is_deleted", "-created_at"], name="cases_is_dele_65745b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="case",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "evaluated", "awaiting_review", "reviewed", "closed"],
                    )
                ),
                name="valid_case_status",
            ),
        ),
        migrations.AddIndex(
            model_name="casefact",
            index=models.Index(
                fields=["case", "fact_key"], name="case_facts_case_id_2bed14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casefact",
            index=models.Index(
                fields=["fact_key", "-created_at"], name="case_facts_fact_ke_9f3d28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestatushistory",
            index=models.Index(
                fields=["case", "-created_at"], name="case_status_case_id_16ed8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestatushistory",
            index=models.Index(
                fields=["changed_by", "-created_at"],
                name="case_status_changed_4b8eba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casestatushistory",
            index=models.Index(
                fields=["new_status", "-created_at"],
                name="case_status_new_sta_ec1b8a_idx",
            ),
        ),
    ]
