# Generated by Django 5.2.10 on 2026-01-14 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecisionOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overridden_outcome",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("not_eligible", "Not Eligible"),
                            ("requires_review", "Requires Review"),
                        ],
                        db_index=True,
                        help_text="The new outcome after override",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the override")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Decision Overrides",
                "db_table": "decision_overrides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the review",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the review was assigned",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the review was completed",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Version number for optimistic locking",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(help_text="The note content")),
                (
                    "is_internal",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this note is internal (not visible to user)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Review Notes",
                "db_table": "review_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status before change",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        help_text="New status after change", max_length=20
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the status change", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the status change",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Review Status History",
                "db_table": "review_status_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
