# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_decisions", "0003_initial"),
        ("human_reviews", "0001_initial"),
        ("immigration_cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionoverride",
            name="case",
            field=models.ForeignKey(
                help_text="The case this override applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_overrides",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="decisionoverride",
            name="original_result",
            field=models.ForeignKey(
                help_text="The original AI eligibility result being overridden",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="ai_decisions.eligibilityresult",
            ),
        ),
    ]
