# Generated by Django 5.2.10 on 2026-01-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("human_reviews", "0002_initial"),
        ("immigration_cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionoverride",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="The reviewer who made the override",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decision_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="case",
            field=models.ForeignKey(
                help_text="The case being reviewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="immigration_cases.case",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="The reviewer assigned to this review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewnote",
            name="review",
            field=models.ForeignKey(
                help_text="The review this note belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="human_reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the status change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewstatushistory",
            name="review",
            field=models.ForeignKey(
                help_text="The review this status change belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="human_reviews.review",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionoverride",
            index=models.Index(
                fields=["case", "-created_at"], name="decision_ov_case_id_9d1c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisionoverride",
            index=models.Index(
                fields=["original_result", "-created_at"],
                name="decision_ov_origina_238186_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["case", "status"], name="reviews_case_id_a2a5e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "status"], name="reviews_reviewe_fdb5b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewstatushistory",
            index=models.Index(
                fields=["review", "-created_at"], name="review_stat_review__c962c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewstatushistory",
            index=models.Index(
                fields=["changed_by", "-created_at"],
                name="review_stat_changed_6418b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewstatushistory",
            index=models.Index(
                fields=["new_status", "-created_at"],
                name="review_stat_new_sta_dbaccf_idx",
            ),
        ),
    ]
