# Generated by Django 5.2.10 on 2026-01-14 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_handling', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_type', models.CharField(choices=[('ocr', 'OCR'), ('classification', 'Classification'), ('validation', 'Validation'), ('full', 'Full Processing'), ('reprocess', 'Reprocess')], db_index=True, help_text='Type of processing to perform', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the processing job', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking', max_length=255, null=True)),
                ('priority', models.IntegerField(default=5, help_text='Job priority (1-10, higher is more urgent)')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('error_type', models.CharField(blank=True, db_index=True, help_text='Type of error if processing failed', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (processing time, tokens used, cost, etc.)', null=True)),
                ('llm_tokens_used', models.IntegerField(blank=True, help_text='Number of LLM tokens used', null=True)),
                ('llm_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='LLM cost in USD', max_digits=10, null=True)),
                ('ocr_cost_usd', models.DecimalField(blank=True, decimal_places=6, help_text='OCR cost in USD', max_digits=10, null=True)),
                ('total_cost_usd', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Total processing cost in USD', max_digits=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When processing completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_document', models.ForeignKey(help_text='The document being processed', on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='document_handling.casedocument')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this job (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processing Jobs',
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ocr_started', 'OCR Started'), ('ocr_completed', 'OCR Completed'), ('ocr_failed', 'OCR Failed'), ('classification_started', 'Classification Started'), ('classification_completed', 'Classification Completed'), ('classification_failed', 'Classification Failed'), ('validation_started', 'Validation Started'), ('validation_completed', 'Validation Completed'), ('validation_failed', 'Validation Failed'), ('job_created', 'Job Created'), ('job_queued', 'Job Queued'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_failed', 'Job Failed'), ('job_cancelled', 'Job Cancelled'), ('retry_attempted', 'Retry Attempted'), ('manual_override', 'Manual Override')], db_index=True, help_text='Action performed', max_length=50)),
                ('status', models.CharField(db_index=True, help_text='Status: success, failure, warning', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Human-readable message', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (processing time, tokens, cost, confidence, etc.)', null=True)),
                ('error_type', models.CharField(blank=True, db_index=True, help_text='Error type if action failed', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case_document', models.ForeignKey(help_text='Document being processed', on_delete=django.db.models.deletion.CASCADE, related_name='processing_history', to='document_handling.casedocument')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_history_entries', to=settings.AUTH_USER_MODEL)),
                ('processing_job', models.ForeignKey(blank=True, help_text='Processing job this history entry belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='document_processing.processingjob')),
            ],
            options={
                'verbose_name_plural': 'Processing History',
                'db_table': 'processing_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['case_document', 'status'], name='processing__case_do_60ef42_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='processing__status_183f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['processing_type', 'status'], name='processing__process_11781f_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['celery_task_id'], name='processing__celery__4245d2_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['error_type'], name='processing__error_t_270406_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['case_document', 'action'], name='processing__case_do_7f2a42_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['processing_job', 'action'], name='processing__process_3429a2_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['action', 'status'], name='processing__action_b00bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['created_at', 'status'], name='processing__created_276c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='processinghistory',
            index=models.Index(fields=['error_type'], name='processing__error_t_144cfa_idx'),
        ),
    ]
